### ISSUE TITLE
Electors not reallocated from states with zero population

### ISSUE THREAD

**Issue by herbiemarkwort** [khwilson/RedrawStates#1] opened 2016-11-29 06:42 UTC
Let's say you think all 3 counties of Delaware should belong to Maryland. After moving the counties to Maryland, Delaware no longer exists. However, the code does not recognize that Delaware no longer exists and continues to allocate 3 electors to the state.

**Comment by khwilson** [comment] 2016-11-29 14:02
Thanks for the interest!

Yeah, this is a flaw. Also just try moving Alaska anywhere.

The problem is that the apportionment algorithm begins by allocating each state one representative. If a state has no population, really it just shouldn't exist anymore.

I'd welcome a PR with an "add state" or "remove state" feature. But, tbh, at that point I'm pretty far down the path of building "Sim Congressional District", and that's a bit farther than I personally want to take this project.

**Comment by khwilson** [comment] 2016-11-30 14:55
Thanks so much for the PR. I'll close this for now, but there really should be an "add state feature now.

**Closed as completed by khwilson** 2016-11-30 14:55 UTC
